#!/bin/bash
docker run -t --rm \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
	-e DISPLAY=unix$DISPLAY \
	-p 443:443 \
	-p 17992:17992 \
	-p 17990:17990 \
	-v /dev/shm:/dev/shm \
    -v /etc/machine-id:/etc/machine-id \
    -v /run/user/$UID/pulse:/run/user/$UID/pulse \
    -v /var/lib/dbus:/var/lib/dbus \
	vidyo

	#-p 443:443 \
	#-p 17992:17992 \
	#-p 17990:17990 \
	#-p 50000-65535:50000-65535 \
