FROM fedora:21
MAINTAINER Marco Boretto  marco.boretto@cern.ch marco.bore@gmail.com

# Update system... 
# Please notice that this is in general not recomendable, 
# since you are not controlling which version of the software 
# will be installed on your system.
# This may cause not predictable misbehaviours.
#RUN yum update -y && yum clean all

# Install prerequisites.
RUN yum install eclipse libcanberra-gtk3 -y

RUN yum install wget tar file mlocate vim htop unzip\
    psmisc procps-ng \
#    bind-utils net-tools tcpreplay pcapfix iputils nc \
    bind-utils net-tools tcpreplay pcapfix nc \
    git gcc-c++ make \
    valgrind gdb \
    tbb tbb-devel boost boost-devel \
    glog glog-devel gflags-devel \
    cppzmq-devel libpcap libpcap-devel \
    gperftools gperftools-libs \ 
#Those are required from DIM
    tcsh motif-devel -y

#due to a docker bug problem wireshark is not working
#RUN yum install wireshark -y
#wireshark provided by seems not work..
#RUN rpm -ivh ftp://fr2.rpmfind.net/linux/fedora/linux/updates/testing/22/x86_64/w/wireshark-1.12.8-1.fc22.x86_64.rpm



#Adding some pfring include needed to compile
ADD usr/include/linux/pf_ring.h /usr/include/linux/
ADD usr/local/include/pfring.h /usr/local/include/

#installing DIM
ADD compileDIM /compileDIM

#DIM is compiled in  tcsh environment as described in the official documentation
RUN ./compileDIM && \
#a sort of make install
	cp -R /dim_v20r15/dim/ /usr/local/include/ && \
	cp /dim_v20r15/obj/libdim.* /usr/local/lib/

#Move farm configuration files
ADD etc/na62-farm.cfg /etc/na62-farm.cfg
ADD etc/na62-trigger.conf /etc/na62-trigger.conf
  
#update the locate db
RUN updatedb

WORKDIR /root
CMD /bin/bash
