#!/bin/bash
#docker run -ti --rm -e DISPLAY=$DISPLAY \
#    -v `pwd`/.eclipse:/home/developer/.eclipse \
#	-v /tmp/.X11-unix:/tmp/.X11-unix \
#	na62-farm



docker run -ti --rm -e DISPLAY=$DISPLAY \
    -v `pwd`/developer:/home/developer \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	na62-farm
