#!/bin/bash

DOCKUSERNAME='developer'
docker run -ti --rm \
    -v `pwd`/${DOCKUSERNAME}:/home/${DOCKUSERNAME} \
	-v /tmp/.X11-unix:/tmp/.X11-unix \
	-e DISPLAY=unix$DISPLAY \
    -name na62-farm1 \
	na62-farm

#docker run -ti --rm \
#   -v `pwd`/root:/root \
#   -v /tmp/.X11-unix:/tmp/.X11-unix \
#   -e DISPLAY=unix$DISPLAY \
#   --security-opt "apparmor:docker-ptrace" \
#	na62-farm

